Changed entities Order, Product and CreatedProduct
LizzardCorp/pv243project pull request #8
Opened 2018-04-04 22:04 UTC by pajavyskocil

* Changed Table name in Order Entity
* Removed JoinColumn and Lazy fetch type from CreatedProduct Entity
* Added attribute createdProducts and methods: getProductCategories, getCreatedProducts, addCreatedProduct and removeCreatedProduct
* Added methods:getSubmittedOrders, addSubmittedOrder and removeSubmittedOrder
* Changed Enities to return unmodifiableSet

2018-04-05 08:46 UTC, balcirakpeter requested changes

2018-04-05 08:46 UTC, balcirakpeter commented on TACOS-persistence/src/main/java/cz/fi/muni/TACOS/persistence/entity/User.java
> +        return submittedOrders;
You forgot to use unmodifiableSet method.

2018-04-05 08:46 UTC, balcirakpeter commented on TACOS-persistence/src/main/java/cz/fi/muni/TACOS/persistence/entity/CreatedProduct.java
> +    @ManyToOne
Please add @Column(nullable = false)

2018-04-05 08:46 UTC, balcirakpeter commented on TACOS-persistence/src/main/java/cz/fi/muni/TACOS/persistence/entity/CreatedProduct.java
> +    @ManyToOne
Please add @Column(nullable = false)

2018-04-05 14:24 UTC, vyskocilpavel commented on TACOS-persistence/src/main/java/cz/fi/muni/TACOS/persistence/entity/CreatedProduct.java
> +    @ManyToOne
@Column(s) not allowed on a @ManyToOne property:

2018-04-05 14:24 UTC, vyskocilpavel commented on TACOS-persistence/src/main/java/cz/fi/muni/TACOS/persistence/entity/CreatedProduct.java
> +    @ManyToOne
@Column(s) not allowed on a @ManyToOne property:

2018-04-06 09:49 UTC, balcirakpeter approved these changes

2018-04-06 09:50 UTC, merged